"""
Downloads MBPP (sanitized) directly from GitHub, converts problems into this
project's task schema (id, problem, entry_point, test_code), verifies each
one against MBPP's own reference code, and writes mbpp_tasks.py.

MBPP sanitized format gives us `prompt` (a one-line NL description), `code`
(a reference solution), and `test_list` (assert strings that call the
function by its real name, not "candidate"). We:
  1. Use `prompt` directly as `problem`.
  2. Derive `entry_point` from the `def <name>(` in `code`.
  3. Build `test_code` that binds the submitted function under that name in
     a local namespace, then runs each assert from test_list against it.
  4. Verify by exec'ing the reference `code` and running our test_code
     against it -- drop the task if the reference doesn't pass.
"""

import json
import re
import urllib.request

SOURCE_URL = "https://raw.githubusercontent.com/google-research/google-research/master/mbpp/sanitized-mbpp.json"
OUTPUT_PATH = "mbpp_tasks.py"
LIMIT = 427  # full sanitized MBPP pool -- see convert_humaneval.py for why this
             # was deliberately raised from the original 40


def fetch_problems():
    with urllib.request.urlopen(SOURCE_URL) as resp:
        data = json.loads(resp.read().decode("utf-8"))
    return data


def derive_entry_point(code: str) -> str | None:
    match = re.search(r"^def\s+(\w+)\s*\(", code, re.MULTILINE)
    return match.group(1) if match else None


def build_test_code(entry_point: str, test_imports, test_list) -> str:
    imports = "\n".join(test_imports)
    asserts = "\n".join(f"    {line}" for line in test_list)
    return f'''
{imports}

def test(fn):
    {entry_point} = fn
{asserts}
    return True
'''


def verify(code: str, test_code: str, entry_point: str) -> bool:
    namespace = {}
    try:
        exec(code, namespace)
        exec(test_code, namespace)
        fn = namespace.get(entry_point)
        if fn is None:
            return False
        return bool(namespace["test"](fn))
    except Exception as e:
        print(f"  verification failed: {e}")
        return False


def main():
    print(f"Downloading MBPP (sanitized) from {SOURCE_URL} ...")
    problems = fetch_problems()
    print(f"Fetched {len(problems)} total MBPP problems.")

    converted = []
    for prob in problems:
        if len(converted) >= LIMIT:
            break

        task_id = prob["task_id"]
        code = prob["code"]
        entry_point = derive_entry_point(code)
        if entry_point is None:
            print(f"  SKIP mbpp_{task_id}: could not derive entry_point from code")
            continue

        problem_text = prob["prompt"].strip()
        test_code = build_test_code(entry_point, prob.get("test_imports", []), prob["test_list"])

        ok = verify(code, test_code, entry_point)
        if not ok:
            print(f"  SKIP mbpp_{task_id}: failed verification against reference solution")
            continue

        converted.append({
            "id": f"mbpp_{task_id:03d}",
            "problem": problem_text,
            "entry_point": entry_point,
            "test_code": test_code,
            "source": "mbpp",
        })
        print(f"  OK mbpp_{task_id} -> {entry_point}")

    if len(converted) < LIMIT:
        print(f"\nWARNING: only {len(converted)}/{LIMIT} problems verified successfully. "
              f"Writing what we have -- check output before merging.")

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write('"""\n')
        f.write(f"Auto-generated by convert_mbpp.py from MBPP sanitized ({SOURCE_URL}).\n")
        f.write(f"{len(converted)} problems, each verified against MBPP's own "
                 f"reference solution.\nSchema matches tasks/coding_tasks.py.\n")
        f.write('"""\n\n')
        f.write("MBPP_TASKS = [\n")
        for t in converted:
            f.write("    {\n")
            f.write(f"        \"id\": {t['id']!r},\n")
            f.write(f"        \"problem\": {t['problem']!r},\n")
            f.write(f"        \"entry_point\": {t['entry_point']!r},\n")
            f.write(f"        \"test_code\": {t['test_code']!r},\n")
            f.write(f"        \"source\": {t['source']!r},\n")
            f.write("    },\n")
        f.write("]\n")

    print(f"\nWrote {len(converted)} tasks to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
