"""
Downloads HumanEval directly from GitHub, converts problems into this
project's task schema (id, problem, entry_point, test_code), verifies each
one against HumanEval's own reference solution, and writes humaneval_tasks.py.

Schema match with tasks/coding_tasks.py:
  - id: unique task identifier ("he_XXX")
  - problem: natural-language problem statement given to Agent A
  - entry_point: function name Agent B's code must define
  - test_code: Python code defining test(fn) -> bool

HumanEval's own format gives us `prompt` (signature + docstring), `canonical_
solution`, `test` (a check(candidate) function), and `entry_point`. We:
  1. Build `problem` from the prompt's docstring (natural language only --
     not the function signature, so Agent A has to write a real handoff
     instead of just echoing the signature back).
  2. Build `test_code` by wrapping HumanEval's check(candidate) into our
     test(fn) -> bool shape.
  3. Verify by exec'ing prompt + canonical_solution and running our test_code
     against it -- if the reference solution doesn't pass, we drop the task
     rather than ship something broken.
"""

import gzip
import io
import json
import re
import urllib.request

SOURCE_URL = "https://raw.githubusercontent.com/openai/human-eval/master/data/HumanEval.jsonl.gz"
OUTPUT_PATH = "humaneval_tasks.py"
LIMIT = 164  # full HumanEval pool -- deliberately raised from 30 to grow subgroup
             # sample sizes (see entity_omission n=8 discussion); this reverses
             # DATA_PREP_INSTRUCTIONS.md's original "don't use the full pool"
             # guidance, which optimized for a different goal (data-collection
             # efficiency) than this later goal (statistical robustness of
             # small subgroups)


def fetch_problems():
    with urllib.request.urlopen(SOURCE_URL) as resp:
        raw = resp.read()
    with gzip.GzipFile(fileobj=io.BytesIO(raw)) as gz:
        text = gz.read().decode("utf-8")
    problems = [json.loads(line) for line in text.splitlines() if line.strip()]
    return problems


def extract_docstring(prompt: str) -> str:
    """Pulls just the natural-language docstring out of a HumanEval prompt,
    dropping the function signature/type hints so Agent A has to actually
    describe the problem instead of forwarding the signature verbatim."""
    match = re.search(r'"""(.*?)"""', prompt, re.DOTALL) or re.search(r"'''(.*?)'''", prompt, re.DOTALL)
    if not match:
        return prompt.strip()
    doc = match.group(1).strip()
    # collapse internal blank-line-heavy indentation from the docstring block
    lines = [ln.strip() for ln in doc.splitlines()]
    return "\n".join(ln for ln in lines if ln)


def build_test_code(entry_point: str, check_code: str) -> str:
    """HumanEval's `test` field defines check(candidate). We wrap it so it
    matches this project's test(fn) -> bool contract."""
    return f'''
{check_code}

def test(fn):
    check(fn)
    return True
'''


def verify(prompt: str, canonical_solution: str, entry_point: str, test_code: str) -> bool:
    namespace = {}
    try:
        exec(prompt + canonical_solution, namespace)
        exec(test_code, namespace)
        fn = namespace.get(entry_point)
        if fn is None:
            return False
        return bool(namespace["test"](fn))
    except Exception as e:
        print(f"  verification failed: {e}")
        return False


def main():
    print(f"Downloading HumanEval from {SOURCE_URL} ...")
    problems = fetch_problems()
    print(f"Fetched {len(problems)} total HumanEval problems.")

    converted = []
    for prob in problems:
        if len(converted) >= LIMIT:
            break

        task_id = prob["task_id"]  # e.g. "HumanEval/12"
        entry_point = prob["entry_point"]
        problem_text = extract_docstring(prob["prompt"])
        test_code = build_test_code(entry_point, prob["test"])

        ok = verify(prob["prompt"], prob["canonical_solution"], entry_point, test_code)
        if not ok:
            print(f"  SKIP {task_id}: failed verification against reference solution")
            continue

        num = task_id.split("/")[-1]
        converted.append({
            "id": f"he_{int(num):03d}",
            "problem": problem_text,
            "entry_point": entry_point,
            "test_code": test_code,
            "source": "humaneval",
        })
        print(f"  OK {task_id} -> he_{int(num):03d}")

    if len(converted) < LIMIT:
        print(f"\nWARNING: only {len(converted)}/{LIMIT} problems verified successfully. "
              f"Writing what we have -- check output before merging.")

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write('"""\n')
        f.write(f"Auto-generated by convert_humaneval.py from HumanEval "
                 f"({SOURCE_URL}).\n")
        f.write(f"{len(converted)} problems, each verified against HumanEval's own "
                 f"reference solution.\nSchema matches tasks/coding_tasks.py.\n")
        f.write('"""\n\n')
        f.write("HUMANEVAL_TASKS = [\n")
        for t in converted:
            f.write("    {\n")
            f.write(f"        \"id\": {t['id']!r},\n")
            f.write(f"        \"problem\": {t['problem']!r},\n")
            f.write(f"        \"entry_point\": {t['entry_point']!r},\n")
            f.write(f"        \"test_code\": {t['test_code']!r},\n")
            f.write(f"        \"source\": {t['source']!r},\n")
            f.write("    },\n")
        f.write("]\n")

    print(f"\nWrote {len(converted)} tasks to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
