"""
run_corruptions.py
------------------
Phase 2 of the corruption pipeline.

Reads corrupted_handoffs.csv (generated by generate_corruptions.py), runs
Agent B on each corrupted handoff via the Gemini API in parallel (one worker
per API key), grades each result against the original unit tests, and writes
results to step5_corruption_results.csv.

Label logic
-----------
  label = 0  → corruption BROKE Agent B  (strong negative, useful training signal)
  label = 1  → corruption did NOT break Agent B  (weak negative, still saved with flag)

Both outcomes are written so the full picture is preserved; downstream
feature extraction can filter on label or weak_negative as needed.

Resume safety
-------------
Already-written (task_id, corruption_type) pairs are skipped on re-run,
so a quota-hit mid-run doesn't lose progress.  Each result is flushed
to disk immediately after grading.

Usage
-----
    python run_corruptions.py              # dry-run — prints plan, no API calls
    python run_corruptions.py --execute    # live run
"""

import argparse
import csv
import os
import sys
import time
import traceback
from concurrent.futures import ThreadPoolExecutor, as_completed

sys.path.insert(0, ".")

from tasks.curated_250 import CURATED_250
from agents import agent_b_code, N_KEYS, MODEL_B, QuotaExhausted
from rollout_runner import grade

# ─── Config ───────────────────────────────────────────────────────────────────

INPUT_CSV  = "corrupted_handoffs.csv"
OUTPUT_CSV = "step5_corruption_results.csv"

FIELDNAMES = [
    "task_id", "problem", "original_handoff", "handoff",
    "corruption_type", "label", "label_source",
    "weak_negative", "entry_point", "source",
]

N_WORKERS = N_KEYS   # one worker per API key → true parallelism

# ─── Task lookup ──────────────────────────────────────────────────────────────

_task_lookup = {t["id"]: t for t in CURATED_250}


# ─── Helpers ──────────────────────────────────────────────────────────────────

def load_corrupted_rows(path: str) -> list[dict]:
    """Load all rows from corrupted_handoffs.csv."""
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"{path} not found — run generate_corruptions.py first."
        )
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def load_already_done(path: str) -> set:
    """(task_id, corruption_type) pairs already written to output CSV."""
    if not os.path.exists(path) or os.path.getsize(path) == 0:
        return set()
    with open(path, newline="", encoding="utf-8") as f:
        return {
            (r["task_id"], r["corruption_type"])
            for r in csv.DictReader(f)
            if r.get("task_id") and r.get("corruption_type")
        }


def _open_writer(path: str):
    is_new = not os.path.exists(path) or os.path.getsize(path) == 0
    f = open(path, "a", newline="", encoding="utf-8")
    w = csv.DictWriter(f, fieldnames=FIELDNAMES)
    if is_new:
        w.writeheader()
    return f, w


# ─── Per-task worker (runs in a thread) ───────────────────────────────────────

def process_row(row: dict) -> dict:
    """
    Run Agent B on one corrupted handoff, grade it, return a result dict.
    Called from multiple threads simultaneously — thread-safe via _POOL.
    """
    tid         = row["task_id"]
    handoff     = row["handoff"]
    ctype       = row["corruption_type"]
    entry_point = row.get("entry_point", "")
    problem     = row.get("problem", "")
    source      = row.get("source", "")
    orig_handoff = row.get("original_handoff", "")

    # Fetch test_code from curated task list
    task_info = _task_lookup.get(tid, {})
    test_code = task_info.get("test_code", "")

    t_start = time.monotonic()
    try:
        code   = agent_b_code(handoff, entry_point)
        passed = grade(code, entry_point, test_code)
    except QuotaExhausted:
        raise   # bubble up to stop the run
    except Exception as exc:
        return {
            "task_id":   tid,
            "ctype":     ctype,
            "ok":        False,
            "error":     str(exc),
            "elapsed":   time.monotonic() - t_start,
            "csv_row":   None,
        }

    # label=0: corruption BROKE Agent B (strong negative)
    # label=1: corruption did NOT break Agent B (weak negative — record but flag)
    label        = 0 if not passed else 1
    weak_negative = 1 if passed else 0

    return {
        "task_id":  tid,
        "ctype":    ctype,
        "ok":       True,
        "passed":   passed,
        "elapsed":  time.monotonic() - t_start,
        "csv_row": {
            "task_id":          tid,
            "problem":          problem,
            "original_handoff": orig_handoff,
            "handoff":          handoff,
            "corruption_type":  ctype,
            "label":            label,
            "label_source":     "measured",
            "weak_negative":    weak_negative,
            "entry_point":      entry_point,
            "source":           source,
        },
    }


# ─── Main ─────────────────────────────────────────────────────────────────────

import concurrent.futures

def main(dry_run: bool = True):
    all_rows    = load_corrupted_rows(INPUT_CSV)
    already_done = load_already_done(OUTPUT_CSV)

    # Filter to rows we still need to process
    pending = [
        r for r in all_rows
        if (r["task_id"], r["corruption_type"]) not in already_done
    ]
    skipped = len(all_rows) - len(pending)

    # Count breakdown by corruption type
    from collections import Counter
    ctype_counts = Counter(r["corruption_type"] for r in pending)

    print("=" * 64)
    print("  Step 5 — Corruption API runner")
    print(f"  Model        : {MODEL_B}")
    print(f"  API keys     : {N_KEYS}  (workers = {N_WORKERS})")
    print(f"  Input CSV    : {INPUT_CSV}")
    print(f"  Total rows   : {len(all_rows)}")
    print(f"  Already done : {skipped}")
    print(f"  To process   : {len(pending)}")
    print(f"  Output CSV   : {OUTPUT_CSV}")
    print("  By corruption type:")
    for ct, n in sorted(ctype_counts.items()):
        print(f"    {ct:<30} {n}")
    print("=" * 64)

    if dry_run:
        print("\n  DRY RUN — no API calls made.")
        print("  Pass --execute to actually run.\n")
        if pending:
            print("  First 5 tasks queued:")
            for r in pending[:5]:
                print(f"    {r['task_id']:<15} {r['corruption_type']}")
        return

    if not pending:
        print("\n  Nothing to do — all rows already in output CSV.\n")
        return

    # ── Execute ──
    f, writer  = _open_writer(OUTPUT_CSV)
    n_broke    = 0   # corruption caused failure (label=0, strong negative)
    n_survived = 0   # corruption did NOT break Agent B (weak negative)
    n_err      = 0
    quota_hit  = False
    wall_start = time.monotonic()

    try:
        with ThreadPoolExecutor(max_workers=N_WORKERS) as executor:
            futures = {
                executor.submit(process_row, row): (row["task_id"], row["corruption_type"])
                for row in pending
            }

            for future in as_completed(futures):
                tid, ctype = futures[future]
                try:
                    result = future.result()
                except QuotaExhausted as exc:
                    if not quota_hit:
                        print(f"\n  QUOTA HIT: {exc}")
                        print("  Cancelling pending; draining completed results...")
                        quota_hit = True
                        for fut in futures:
                            fut.cancel()
                    n_err += 1
                    continue
                except concurrent.futures.CancelledError:
                    # Future was cancelled during quota-hit drain — expected, skip silently.
                    n_err += 1
                    continue
                except Exception:
                    print(f"  ERROR  {tid}/{ctype}")
                    traceback.print_exc()
                    n_err += 1
                    continue

                if not result["ok"]:
                    print(f"  ERROR  {tid}/{ctype}  ({result['elapsed']:.1f}s)  {result['error']}")
                    n_err += 1
                    continue

                status = "BROKE" if not result["passed"] else "survived"
                print(f"  [{status:<8}]  {tid:<15} {ctype}  ({result['elapsed']:.1f}s)")

                if result["passed"]:
                    n_survived += 1
                else:
                    n_broke += 1

                # Write immediately — every flush is a checkpoint.
                # On re-run, load_already_done() skips these (task_id, ctype) pairs.
                writer.writerow(result["csv_row"])
                f.flush()

    finally:
        f.close()

    wall = time.monotonic() - wall_start
    print()
    print("=" * 64)
    print(f"  Done in {wall:.0f}s")
    print(f"  BROKE Agent B  (label=0, strong neg) : {n_broke}")
    print(f"  Survived       (label=1, weak neg)   : {n_survived}")
    print(f"  Errors (skip)                        : {n_err}")
    if quota_hit:
        print("  !! Quota hit — re-run to resume (already-done pairs are skipped)")
    print(f"  Results in : {OUTPUT_CSV}")
    print("=" * 64)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--execute",
        action="store_true",
        help="Actually run Agent B on corrupted handoffs. Without this flag it's a dry-run.",
    )
    args = parser.parse_args()
    main(dry_run=not args.execute)
