"""
Merges every task source into one list for rollout_runner.py.

tasks/coding_tasks.py contains the original 60 hand-crafted tasks (task_001-
030 = hand_easy, task_031-060 = hand_hard). tasks/hard_tasks_3.py adds 24
more hand-crafted tasks (task_061-084), written with named entities and
explicit edge-case language to grow the entity_omission corruption's
trigger surface. humaneval_tasks.py and mbpp_tasks.py are generated by
convert_humaneval.py / convert_mbpp.py, now at their full pool sizes (164
and 427 respectively) rather than the original 30/40 subset -- deliberately
scaled up to grow subgroup sample sizes for the robustness analysis. All
five sources carry their own "source" field.
"""

from tasks.coding_tasks import TASKS as hand_crafted
from tasks.hard_tasks_3 import HARD_TASKS_3 as hand_crafted_extra
from humaneval_tasks import HUMANEVAL_TASKS as humaneval
from mbpp_tasks import MBPP_TASKS as mbpp

ALL_TASKS = hand_crafted + hand_crafted_extra + humaneval + mbpp
