"""
Merges every task source into one list for rollout_runner.py.

tasks/coding_tasks.py already contains the 60 hand-crafted tasks (task_001-
030 = hand_easy, task_031-060 = hand_hard) tagged with a "source" field.
humaneval_tasks.py and mbpp_tasks.py are generated by convert_humaneval.py /
convert_mbpp.py and already carry their own "source" field too.
"""

from tasks.coding_tasks import TASKS as hand_crafted
from humaneval_tasks import HUMANEVAL_TASKS as humaneval
from mbpp_tasks import MBPP_TASKS as mbpp

ALL_TASKS = hand_crafted + humaneval + mbpp
